### ISSUE TITLE
Autocomplete => unable to fetch fixtures which are in Camelcase

### ISSUE THREAD

**Issue by dineshpando** [praegus/toolchain-fitnesse-plugin#18]
Currently all my fixtures (java functions )are defined in Camelcase. In this case if i try to fill fixture  using autocomplete camelcase fixture not working as expected

Example fixtures
_public static void launchBrowser(String pageUrl)_ 
_public boolean isElementPresent(String elementIdentifier, String findBy)_
_public void waitForElementToBeDisplayed(String elementIdentifier,String findBy, String timeOut)_

In WikiPage  it display like
<img width="762" alt="Screenshot 2020-06-21 at 5 00 22 PM" src="https://user-images.githubusercontent.com/43804558/85223431-c527fd80-b3e0-11ea-96e3-0b762721c984.png">

Also it will be helpful to auto complete fixture argument instead of fixture datatypes argument

Please let me know if u need more details.

**Comment by tcnh** [comment]
Hi, AutoCompleteResponder fetches these methods just fine. However, bootstrap-plus does some assumptions when there are multiple arguments to a function. `isElementPresent(Str, Str)` is actually in your screenshot, but rendered as: `| is element | [String] | present | [String] |`, because -and I realise this in an opinionated interface- it assumes your methods are written to be used as readable sentences, where camel casing is split using spaces, and alternating cells are concatenated to the method name and arguments.

Also, you can get the argument name in autocomplete, but you'll have to add a javadoc step with our doclet (https://github.com/praegus/fixture-doc-generator) to your fixture project (as argument names are no longer present when the clasdses have been compiled ) That doclet will add a json file containing javadoc info to your jar. This will also:
- Include any javadoc and expose it in context helper
- Allow you to define a string formatted as `usage: | yourPreferredWikiNotation; | Argument1, SomeArgName |` to control what autocomplete indexes for this particular method.

**Comment by dineshpando** [comment]
Thanks @tcnh will try this and let u know

**Comment by dineshpando** [comment]
@tcnh implemented as you mentioned and its working like a charm
<img width="410" alt="Screenshot 2020-06-24 at 10 57 32 AM" src="https://user-images.githubusercontent.com/43804558/85504419-a3f62580-b609-11ea-936b-ee62ea9f2df3.png">
<img width="575" alt="Screenshot 2020-06-24 at 10 56 15 AM" src="https://user-images.githubusercontent.com/43804558/85504427-a9ec0680-b609-11ea-94d3-435321a08d1c.png">

minor issue is not taking up _semicolon ;_ in fixture if i use my defined pattern. but i will look into tht

Fitnesse is moving to next level with ur contribution. Thanks :)

Will close this issue

**Comment by tcnh** [comment]
Hi @dineshpando Good to see you got it running! I'll look into the issue of the disappearing semicolon. That shouldn't happen. I'll also see if I can make Sequential Argument Processing notation an option/switch, so you don't need to explicitly define usage strings in javadoc in order to use it. Created https://github.com/praegus/toolchain-fitnesse-plugin/issues/19 to put on our backlog.
